# this composes a html publishing service for yocto images and package feeds
version: "3"
services:
  my-yocto-builder:
    image: my-yocto-bitbaker:latest

    # run infinitely and do nothing
    command: /bin/bash -c "while true; do  sleep 1; done"
    # note: entrypoint is an alternative to command directive.
    # however it would bypass sanity checks (implemented in containers
    # entrypoint)

    volumes:
      # Project home dir is mandatory
      - .:/yocto/root
      # "ams" typical local setting
      - cache:/yocto/cache
      # ssh needs to be injected if ssh accessible source is to be pulled
      - ${HOME}/.ssh:/home/yocto/.ssh
      # publish as well
      - publish:/yocto/publish

volumes:
  publish:
    external: true
  cache:
    external: true
